#use_frameworks!
#inhibit_all_warnings!

platform :ios, 9.0

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      
#      if config.name != 'Release'
#        if target.name == 'SJUIKit'
#          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) SJDEBUG'
#        end
#      end
    end
  end
  
#  installer.pod_target_subprojects.each do |project|
#    project.targets.each do |target|
#      target.build_configurations.each do |config|
#        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
#          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#        end
#      end
#    end
#  end
end

target 'SJUIKit_Example' do
    pod 'SJUIKit', :path => '../'

    pod 'MJRefresh'
    #pod 'SJObserverHelper'
    pod 'Masonry'
    pod 'YYModel'
    
  target 'SJUIKit_Tests' do
    inherit! :search_paths

    
  end
end
